### ISSUE TITLE
Data Not Found For SMODE  Platforms or LISTOS Aircraft Platforms

### ISSUE THREAD

**Issue by anabellebr22** [NASA-IMPACT/platform-visualization#9]
Finding LISTOS Data: COULD NOT FIND DATA
- go to CASEI website
- look at what platforms were used for SMODE
    - Long Ez
- go to earth data search and query air based platforms
- search for data that says either platform in the title
- for Long Ez: COULD NOT FIND DATA

Finding SMODE Data: COULD NOT FIND DATA
- go to CASEI website
- look at what platforms were used for SMODE
    - B-200, Twin Otter, G-III
- go to earth data search and query air based platforms
- search for data that says either platform in the title
- for B-200; 
- for Twin Otter:
- for G-III:

**Comment by EJwalker13** [comment]
Will have to select new campaigns
